### ISSUE TITLE
openh264-libs conflict with official openh264 from fedora

### ISSUE THREAD

**Issue by kparal** [negativo17/openh264#1]
Hello, there is a new openh264 repository in Fedora 24 (probably will appear in Fedora 23 in some time as well):
https://bodhi.fedoraproject.org/updates/FEDORA-2016-be775029bd

That repository contains openh264, gstreamer plugin, and firefox plugin:

```
$ sudo dnf repository-packages fedora-cisco-openh264 list
Available Packages
gstreamer1-plugin-openh264.i686              1.6.1-2.fc24                         fedora-cisco-openh264
gstreamer1-plugin-openh264.x86_64            1.6.1-2.fc24                         fedora-cisco-openh264
mozilla-openh264.x86_64                      1.5.2-0.4.git21e44bd.fc24            fedora-cisco-openh264
openh264.i686                                1.5.2-0.4.git21e44bd.fc24            fedora-cisco-openh264
openh264.x86_64                              1.5.2-0.4.git21e44bd.fc24            fedora-cisco-openh264
openh264-devel.i686                          1.5.2-0.4.git21e44bd.fc24            fedora-cisco-openh264
openh264-devel.x86_64                        1.5.2-0.4.git21e44bd.fc24            fedora-cisco-openh264
```

That repository is not enabled by default, but it will be available by default.

The problem is that I want the mozilla plugin installed, but I also installed ffmpeg from your "Handbrake" repository, which pulled `openh264-libs`, and it conflicts:

```
$ sudo dnf install gstreamer1-plugin-openh264 mozilla-openh264
Dependencies resolved.
=======================================================================================================
 Package                       Arch      Version                        Repository                Size
=======================================================================================================
Installing:
 gstreamer1-plugin-openh264    x86_64    1.6.1-2.fc24                   fedora-cisco-openh264     21 k
 mozilla-openh264              x86_64    1.5.2-0.4.git21e44bd.fc24      fedora-cisco-openh264    340 k
 openh264                      x86_64    1.5.2-0.4.git21e44bd.fc24      fedora-cisco-openh264    334 k

Transaction Summary
=======================================================================================================
Install  3 Packages

Total size: 695 k
Installed size: 1.8 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/lib64/libopenh264.so.1 from install of openh264-1.5.2-0.4.git21e44bd.fc24.x86_64 conflicts with file from package openh264-libs-1.5.0-2.fc24.x86_64

Error Summary
-------------
```

Is it possible to solve this somehow? E.g. make your `openh264-libs` just a weak dependency for `ffmpeg`, so that it can be removed and replaced with Fedora's `openh264`. Or dropping `openh264-libs` completely, and requiring the user to enable `fedora-cisco-openh264` repository and pull the codec from it?

**Comment by kparal** [comment]
More information also here:
https://fedoraproject.org/wiki/OpenH264

**Comment by scaronni** [comment]
Hi Kamil,

will look at it. I'm currently travelling around Japan and I will be back
home on the 23rd of may.

How do you know that the repository will be enabled by default? Also the
gstreamer plugin is already included in my gstreamer-plugins-bad rebuild,
so I guess just bumping the epoch is more appropriate here.

Thanks for reporting!

--Simone

**Comment by kparal** [comment]
It's not enabled by default, at least currently. But it's available on disk, so you can easily enable it (and gnome-software/packagekit can even search in it, while the repo is still technically disabled). You can see it if you install latest fedora-repos for F24.

It would be nice if your repos could co-exist with fedora-repos easily, so instead of overriding standard packages (by using higher epoch or such), maybe you could drop those from your repository (while keeping the dependency) and require people to enable `fedora-cisco-openh264` before activating your repo.

**Comment by wis775** [comment]
Having the same problem.

**Comment by zeroepoch** [comment]
Maybe if `openh264-libs` virtually provides `openh264` then the mozilla package will be happy.  Also `gstreamer1-plugins-bad` from negativo17 virtually provides many of the package names from rpmfusion but forgot the nonfree variant.  It fails on install of course.

**Comment by scaronni** [comment]
Hello, sorry for the late reply, I was a bit busy.

Regarding the `gstreamer1-plugins-bad-nonfree` variant, there is another issue open and the updated `gstreamer1-plugins-bad` package has just been uploaded.

I've summarized it here: http://negativo17.org/openh264-firefox-support/

**Comment by zeroepoch** [comment]
Seems to be working now.  At least it's enabled in firefox and thinks it's up to date.
